### PR TITLE
Autopilot

### PR DESCRIPTION
**Pull request by iam4x**
* [x] basic autopilot with google maps directions service
* [x] stop autopilot
* [x] refactor speed counter & distance counter to mesure autopilot
* [x] pause / resume autopilot
* [x] select autopilot speed (simulate walk / bike / drive)

jul-19-2016 22-56-09

### CODE REVIEW

**Comment by elfenars** [comment]
Is it possible also to add a circling autopilot for egg hatching?

**Comment by iam4x** [comment]
@elfenars Will do it after this PR lands 👍

**Comment by WhataShane** [comment]
Could you possible upload a precompiled version of this fork?  Thanks in advance.

**Comment by pascalschwientek** [comment]
You can clone the [autopilot branch](https://github.com/iam4x/pokemongo-webspoof/tree/autopilot) and build this pre-version yourself by running `npm build`

**Comment by g3crossfire** [comment]
when will you upload the newest app update? sounds really good...

**Comment by g3crossfire** [comment]
i don't know how to npm build. when will you release v1.0.3? :)

**Comment by iam4x** [comment]
I'm at work right now, will try to push an update late tonight.

**Comment by g3crossfire** [comment]
Doing a good job iam4x . Amazing what you have made.

**Comment by fsegouin** [comment]
@g3crossfire Just clone with `git clone -b autopilot ...` then run `npm install && npm run build`

**Comment by viperfx** [comment]
@iam4x Can we setup a chat for this repo? I have some improvements coded and I wanted to run them by you.

**Comment by g3crossfire** [comment]
@fsegouin I tried that but when it finished it loaded up a app and Xcode but the app had nothing in it. Just blank. Not sure where I went wrong. But my skills are very limited so maybe I'll need @im4x to post the new app v1.0.3

**Comment by wxrdn** [comment]
So excited to see this PR. Amazing job! Can't wait! :P

**Comment by MoOx** [comment]
Is there an auto pause possible whenever a pokemon appears around? Would be awesome :D
Anyway, thanks for this work @iam4x.

**Comment by KostyaChoporov** [comment]
Awesome!

**Comment by iam4x** [comment]
@MoOx I can't without linking the user account to the Mac app and query directly the pokemongo servers. But I'm not sure it's a good idea since it will be much more easier for them to detect that another client is doing requests to their servers.

Right now it's only spoofing the iOS device GPS without altering the data sent from the Pokémon GO app. And I want it keep it like that 👍

**Comment by iam4x** [comment]
@MoOx Will add support of spacebar to pause/unpause after this 👍 

shipit

**Comment by CrazyJayson** [comment]
@iam4x really awesome work! I wanted to ask if you can just right click the map and activate the autopilot that way? would be nice :+1:

**Comment by iam4x** [comment]
@CrazyJayson can you create an issue for that? Thank's 🙏

**Comment by pol0nium** [comment]
Awesome work! Could you please provide a new release? Thanks.

**Comment by iam4x** [comment]
@pol0nium release: https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.1.0

**Pull request merged**
