### PR TITLE
added auto updates when stationary feature

### PR DESCRIPTION
**Pull request by AlmirKadric**
This should fix issue #339 

Note: I moved the jitter logic to where the `gpx` file is generated to prevent the coordinates deviating too far from where they were originally set.

### CODE REVIEW

**Comment by bateller** [comment]
Great commit, thanks.

One recommendation: randomize the 10000 interval. Otherwise its predictable by Niantic (unless you know the app doesn't call back at least every 10 seconds?).

**Comment by AlmirKadric** [comment]
@bateller fixed

**Comment by MoOx** [comment]
@iam4x would be really nice to have this!

**Comment by bateller** [comment]
Hello,
 I wanted to further expand on my earlier comment.
> Also I pulled the update to my fork and it doesn't seem to be triggering (with toggle on or off, the GPS position never moves)? Haven't had a chance to look why yet but there doesn't seem to be any syntax errors or obvious issues at first glance:
https://github.com/bateller/pokemongo-webspoof

It looks like it is indeed moving coordinates, but not updating the map or the Lat/Long values within the boxes. Would this be possible to add?

Also another crucial thing I noticed... This fork seems to break the "Add randomness to moves" button.

**Comment by AlmirKadric** [comment]
@bateller I'll answer one part at a time:
>It looks like it is indeed moving coordinates, but not updating the map or the Lat/Long values within the boxes. Would this be possible to add?
The reason it doesn't update the lat/long coordiates is that they are directly tied to where the general position of your character should be. We then randomise around this point when writting to the GPX file. We could add a separate part to the screen which displays your current actual position, but those lng lat coordiates should be un-touched IMHO.

>Also another crucial thing I noticed... This fork seems to break the "Add randomness to moves" button.
it doesn't break the add randomness to moves, it just moves it to where the GPX file is created. So even though your lng or lat or point inside the electron map doesn't change, the GPX file and your character will move. To check this open up the gpx file in xcode and check its values. If you keep the "Update even when stationary" option on, you should see that file update ever 1-10 seconds.

And toggling the "Add randomness to moves" will in fact alter the randomness around your current lng lat coordinates.

**Comment by bateller** [comment]
@AlmirKadric 
> It doesn't break the add randomness to moves, it just moves it to where the GPX file is created. So even though your lng or lat or point inside the electron map doesn't change, the GPX file and your character will move. To check this open up the gpx file in xcode and check its values. If you keep the "Update even when stationary" option on, you should see that file update ever 1-10 seconds.

> And toggling the "Add randomness to moves" will in fact alter the randomness around your current lng lat coordinates.

Ahh ok. Thats a good point. If the map isn't updating with the jitter added... then it'd "seem" to not randomize too. So to clarify better I think its safe to say: This commit breaks what is SHOWN in the Lat/Long and on the map in relation to the "Add randomness to moves" button. Although the actual randomness is still in tact (what is what is sent to Xcode).

I do think a feature to add down the road is to show "true" coordinates (being sent to Xcode) in a box or something as you suggested.

**Comment by h4v1nfun** [comment]
lgtm

**Pull request merged**
