### PR TITLE
Update for iOS 12.0

### PR DESCRIPTION
**Pull request by rehne**
didn't worked any longer with the new iOS 12.0
.. at least for me

also updated some node modules

### CODE REVIEW

**Comment by maxfremars** [comment]
looks good. 
i guess, we should not set the target OS to 10 instead of 12. 

I don't think, this pull request gets merged, because there hasn't been any updates for the past 2 years.

**Comment by Masterk78** [comment]
Totally new to this.  Can you provide a few steps on how to edit the files?

**Comment by iam4x** [comment]
Thanks @rehne 👍 

Are you interested of having rights on the repo to push if you are still using the project?

**Comment by rehne** [comment]
@iam4x  yeah sure!

**Pull request merged**
