### PR TITLE
Close autopilot modal with esc

### PR DESCRIPTION
**Pull request by epilande**
#295.

When autopilot modal is open, add event listener to `esc` to close modal.

### CODE REVIEW

**Comment by bbr21** [comment]
@iam4x @epilande : Hi Guys, sorry but could you explain me how to benefits from this new feature ?

Sorry I'm a newbie in here ...

**Comment by epilande** [comment]
@bbr21 This allows you to close the autopilot pop-up with the `esc` key on your keyboard instead of having to press the `cancel` button.

**Comment by bbr21** [comment]
@epilande : Thanks :)
But could you explain me how to implement this ?

**Comment by airliner1975** [comment]
Hi from Vienna!
Is it possible, that a german keyboard-layout (i.e. on a mac book pro) uses different keyCodes?
I'm asking because neither the esc-key nor the spacebar-key for pausing works for me.

**Pull request merged**
