### PR TITLE
Integration https://fastpokemap.se

### PR DESCRIPTION
**Pull request by iam4x**
screen shot 2016-09-14 at 22 47 06

* [x] display pokémons from https://fastpokemap.se
* [x] display pokémons timeleft in human readable
* [x] filter throughs pokémons
* [x] button to force refresh pokémons positions (for instance after a teleport)
* [x] button to toggle pokemon positions on map (cc @h4v1nfun)

### CODE REVIEW

**Comment by iam4x** [comment]
screen shot 2016-09-15 at 17 23 19

<3

**Comment by iworker** [comment]
Nice feature 👍

**Comment by ZuzooVn** [comment]
@iam4x : Can you show the pokestop and gym?

**Comment by MoOx** [comment]
http://pokemongomap.info/ is a good resource for that.

**Pull request merged**
