### PR TITLE
Remove memory warning in iOS App.

### PR DESCRIPTION
**Pull request by h4v1nfun**
Refactor iOS App code.
Remove memory warning in iOS App.

### CODE REVIEW

**Comment by volksport** [comment]
If this actually does the trick this is worth a release asap!

**Comment by iam4x** [comment]
@AbelIngrand Can you review this for me please?

**Comment by AbelIngrand** [comment]
Seems good to me for the refactoring part but I don't see how it fixes the memory warning.

**Comment by AbelIngrand** [comment]
Tested it and confirmed by @nikhdpro in #121

**Comment by iam4x** [comment]
🚢

**Comment by volksport** [comment]
When you get a chance can you cut a release with these changes? Appreciated!

**Comment by danielsantiago** [comment]
I implement the code from https://github.com/iam4x/pokemongo-webspoof/commit/14afe0173ad35376beda3a89a1743d0b0f62af12 and still get the memory proble but around one hour instead of 15 minutes (without the patch). Also because of this I got banned :-/ 

2016-07-22 17:01:17.900 Pokemon WebSpoof[31187:7596456] Received memory warning.
2016-07-22 17:09:05.960 Pokemon WebSpoof[31187:7596456] Received memory warning.
2016-07-22 17:28:00.188 Pokemon WebSpoof[31187:7596456] Received memory warning.
2016-07-22 17:59:01.137 Pokemon WebSpoof[31187:7596456] Received memory warning.
2016-07-22 18:06:44.238 Pokemon WebSpoof[31187:7596456] Received memory warning.
Message from debugger: Terminated due to memory issue

**Comment by h4v1nfun** [comment]
@danielsantiago i'm afraid there's nothing we can do about that. Pokemon Go simply eats too much memory! in my testing i've managed to get about 3h of app open, after a reboot (iPhone 6), then i've got that terminated due to memory issue, but has you can see in xCode app memory stays in the 4.2 ~ 4.7 MB constantly. With a more powerful phone like the 6(+)s or the SE witch both have 2 GB of RAM i don't think this is gonna be a issue.

**Pull request merged**
