### PR TITLE
Use W,A,S,D for navigation in addition to arrow keys

### PR DESCRIPTION
**Pull request by quaertym**

### CODE REVIEW

**Comment by MoOx** [comment]
lgtm

**Comment by MoOx** [comment]
Would be nice to improve this to support azerty layout (so zqsd) too.

**Comment by quaertym** [comment]
@MoOx Done. Ready to merge.

**Comment by JacobBum** [comment]
How can I download this and implement it into the app?

**Comment by MoOx** [comment]
You can clone @quaertym fork, `git checkout patch-1`, then `npm install && npm run dev`.

**Comment by JacobBum** [comment]
@MoOx clone the fork?  Not sure what this means :/ sorry

**Comment by MoOx** [comment]
When a patch is made via github, it's by forking a repo (in our case https://github.com/iam4x/pokemongo-webspoof). This create a duplicate repo where you can do anything you want, and then make a PR (in this case, the current Pull Request).
In the current case, the fork is https://github.com/quaertym/pokemongo-webspoof, so you need following install instructions for developers
https://github.com/iam4x/pokemongo-webspoof#develop and adjust the url

In your case you will have to do in your terminal

```
git clone https://github.com/quaertym/pokemongo-webspoof.git
cd pokemongo-webspoof
git checkout patch-1
npm install
npm run dev
```

Be sure to have node 6 and xcode. If you are not familiar with this, I would advice you to wait for this to be merged and released.

**Comment by JacobBum** [comment]
So lets say for the Space bar to start/stop autopilot, what would the url be that I git clone?  https://github.com/jiangjia/pokemongo-webspoof?

**Comment by MoOx** [comment]
Yep. Add .git at the end to hit the repo and not the HTML page from github (but maybe github automatically fix this for you, I am not sure). Also "git checkout NAMEOFTHEPATCH". In your case "git checkout use-space-bar" when you are in the good directory.

**Comment by JacobBum** [comment]
Gotcha. So after I run this once for the use-space-bar, will it the git file remain like this or will I have to redo this process every time I run the app?

**Comment by MoOx** [comment]
To run the app again, just run "npm run dev" in your folder each time you want to use it.

**Comment by quaertym** [comment]
@MoOx Good to merge?

**Comment by airliner1975** [comment]
Hey Folks!
I tried exactly like @MoOx descriped, but with the command patch-1 I get this error:
pathspec 'patch-1' did not match any file(s) known to git.
What am I doing wrong?

**Comment by MoOx** [comment]
@quaertym sadly I have no rights on this repo, just trying to help for review so when @iam4x came back from vacations, he will be able to rely on community feedback to merge ;)

@airliner1975 you are probably not on the correct fork. You can check the url by doing "git remote -v". If you want, you can add other origin (so others forks) by doing "git remove add NAME URL". Check "git remote --help" for more information. Then you will be able to "git checkout -b patched NAME/patch-1". Hope that helps

**Comment by h4v1nfun** [comment]
lgtm

**Pull request merged**
